### ISSUE TITLE
Replace AHC by Akka Client API (akka-http-core)

### ISSUE THREAD

**Issue by limpid-kzonix** [playframework/play-ws#578] opened 2021-06-16 09:01 UTC
This one is supposed to be under GitHub discussions 
AHC is basically a dead project now since there's no longer an active maintainer
Is a reason to revamp this play-ws library with Akka HTTP Client API as underlying implementation?

**Comment by ihostage** [comment] 2021-06-16 10:49
Looks like a duplicate of #34

**Comment by ihostage** [comment] 2021-06-16 10:53
Moreover, @2m already started work some year ago in #208. 
Maybe in the future, somebody continues this work.

**Closed** 2021-06-18 03:36 UTC
