### ISSUE TITLE
Application does not terminate correctly

### ISSUE THREAD

**Issue by lenalebt** [playframework/play-ws#127] opened 2017-06-06 09:47 UTC
I am using the standalone WS in a script-like program. Sadly, it does not terminate correctly, but hangs. The same happens on a colleagues computer, as well as on the build server, so I doubt it's a local problem for me. I also created a minimal example from the minimal scala seed with `sbt new sbt/scala-seed.g8`.

When terminating with `Ctrl-C`, it will terminate the actor system only after some time.

I used the example code from the README.

### Play WS Version (2.5.x / etc)

`libraryDependencies += "com.typesafe.play" %% "play-ahc-ws-standalone" % "1.0.0-M10"`
but it also happens with RC2.

### API (Scala / Java / Neither / Both)

Scala

### Operating System (Ubuntu 15.10 / MacOS 10.10 / Windows 10)

    Linux fresenius 4.8.0-53-generic #56~16.04.1-Ubuntu SMP Tue May 16 01:18:56 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux

### JDK (Oracle 1.8.0_72, OpenJDK 1.8.x, Azul Zing)

    java version "1.8.0_131"
    Java(TM) SE Runtime Environment (build 1.8.0_131-b11)
    Java HotSpot(TM) 64-Bit Server VM (build 25.131-b11, mixed mode)

### Library Dependencies

none

### Expected Behavior

The application terminates correctly when the main method terminates. An `sbt run` terminates after we receive the "Got a response OK" (see minimal example)

### Actual Behavior

The application does not terminate (within a time frame of <20s). See here:

    $ sbt run
    [info] Loading project definition from /home/brueder/tmp/minimal-ws-error/project
    [info] Set current project to Hello (in build file:/home/brueder/tmp/minimal-ws-error/)
    [info] Running playwsclient.ScalaClient 
    SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
    SLF4J: Defaulting to no-operation (NOP) logger implementation
    SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
    Got a response OK
    ^C[WARN] [06/06/2017 11:03:50.477] [Thread-1] [CoordinatedShutdown(akka://default)] 
    CoordinatedShutdown from JVM shutdown failed: Futures timed out after [10000 milliseconds]

### Reproducible Test Case

see linked minimal example: http://wikisend.com/download/941182/minimal-ws-error.zip

**Comment by marcospereira** [comment] 2017-06-07 13:59
Hey @lenalebt, thanks for the very detailed report.

Apparently, the problem is related to the `registerOnTermination` call. Removing it made everything work as expected, but I didn't have time to better investigate why this is having an impact here. 

Anyway, the problem is not related to play-ws and I'm then closing this issue.

**Closed by marcospereira** 2017-06-07 13:59 UTC

**Comment by lenalebt** [comment] 2017-06-08 07:21
Hey @marcospereira, thanks - that made it work. Although this is not a problem with WS directly, it means that your minimal example in the README is incorrect. I think you should either mention that problem, or remove the code from your example as well, at least until it is fixed elsewhere...

**Comment by marcospereira** [comment] 2017-06-13 18:47
@lenalebt, you are right. Do you want to submit a pull request to update/fix the docs?

**Comment by lenalebt** [comment] 2017-06-14 11:03
Will do. I'll uncomment the code with a remark - this way others who know what the cause is have the chance to contribute. See https://github.com/playframework/play-ws/pull/135

**Comment by gbordyugov** [comment] 2017-12-06 13:19
Can reproduce the bug, PR solves the problem fore me too.
